"use client"
import React from 'react'


const HomePage = () => {

    return (
        <div className=''>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam explicabo libero, eaque officiis deserunt corporis, accusamus, a et earum voluptatem enim mollitia animi totam modi ducimus impedit.<br/>  Deserunt ipsa suscipit libero id! Iusto facere, quibusdam reiciendis iste libero in veniam deserunt repellendus placeat eius, dolorum beatae inventore perspiciatis minus. Voluptates, cum nesciunt laborum nobis inventore tempora enim voluptate aliquam? Praesentium ea cum repellendus veritatis velit, officiis optio nulla! Magni perferendis architecto assumenda quia ad! Inventore iste, quasi mollitia obcaecati eligendi rem! Culpa cum voluptatum suscipit sapiente, natus neque expedita eum ullam, aliquam, dignissimos accusamus omnis ea ipsam odio iusto recusandae!</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam explicabo libero, eaque officiis deserunt corporis, accusamus, a et earum voluptatem enim mollitia animi totam modi ducimus impedit.<br/>  Deserunt ipsa suscipit libero id! Iusto facere, quibusdam reiciendis iste libero in veniam deserunt repellendus placeat eius, dolorum beatae inventore perspiciatis minus. Voluptates, cum nesciunt laborum nobis inventore tempora enim voluptate aliquam? Praesentium ea cum repellendus veritatis velit, officiis optio nulla! Magni perferendis architecto assumenda quia ad! Inventore iste, quasi mollitia obcaecati eligendi rem! Culpa cum voluptatum suscipit sapiente, natus neque expedita eum ullam, aliquam, dignissimos accusamus omnis ea ipsam odio iusto recusandae!</p>

            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam explicabo libero, eaque officiis deserunt corporis, accusamus, a et earum voluptatem enim mollitia animi totam modi ducimus impedit.<br/>  Deserunt ipsa suscipit libero id! Iusto facere, quibusdam reiciendis iste libero in veniam deserunt repellendus placeat eius, dolorum beatae inventore perspiciatis minus. Voluptates, cum nesciunt laborum nobis inventore tempora enim voluptate aliquam? Praesentium ea cum repellendus veritatis velit, officiis optio nulla! Magni perferendis architecto assumenda quia ad! Inventore iste, quasi mollitia obcaecati eligendi rem! Culpa cum voluptatum suscipit sapiente, natus neque expedita eum ullam, aliquam, dignissimos accusamus omnis ea ipsam odio iusto recusandae!</p>

            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam explicabo libero, eaque officiis deserunt corporis, accusamus, a et earum voluptatem enim mollitia animi totam modi ducimus impedit.<br/>  Deserunt ipsa suscipit libero id! Iusto facere, quibusdam reiciendis iste libero in veniam deserunt repellendus placeat eius, dolorum beatae inventore perspiciatis minus. Voluptates, cum nesciunt laborum nobis inventore tempora enim voluptate aliquam? Praesentium ea cum repellendus veritatis velit, officiis optio nulla! Magni perferendis architecto assumenda quia ad! Inventore iste, quasi mollitia obcaecati eligendi rem! Culpa cum voluptatum suscipit sapiente, natus neque expedita eum ullam, aliquam, dignissimos accusamus omnis ea ipsam odio iusto recusandae!</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam explicabo libero, eaque officiis deserunt corporis, accusamus, a et earum voluptatem enim mollitia animi totam modi ducimus impedit.<br/>  Deserunt ipsa suscipit libero id! Iusto facere, quibusdam reiciendis iste libero in veniam deserunt repellendus placeat eius, dolorum beatae inventore perspiciatis minus. Voluptates, cum nesciunt laborum nobis inventore tempora enim voluptate aliquam? Praesentium ea cum repellendus veritatis velit, officiis optio nulla! Magni perferendis architecto assumenda quia ad! Inventore iste, quasi mollitia obcaecati eligendi rem! Culpa cum voluptatum suscipit sapiente, natus neque expedita eum ullam, aliquam, dignissimos accusamus omnis ea ipsam odio iusto recusandae!</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam explicabo libero, eaque officiis deserunt corporis, accusamus, a et earum voluptatem enim mollitia animi totam modi ducimus impedit.<br/>  Deserunt ipsa suscipit libero id! Iusto facere, quibusdam reiciendis iste libero in veniam deserunt repellendus placeat eius, dolorum beatae inventore perspiciatis minus. Voluptates, cum nesciunt laborum nobis inventore tempora enim voluptate aliquam? Praesentium ea cum repellendus veritatis velit, officiis optio nulla! Magni perferendis architecto assumenda quia ad! Inventore iste, quasi mollitia obcaecati eligendi rem! Culpa cum voluptatum suscipit sapiente, natus neque expedita eum ullam, aliquam, dignissimos accusamus omnis ea ipsam odio iusto recusandae!</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam explicabo libero, eaque officiis deserunt corporis, accusamus, a et earum voluptatem enim mollitia animi totam modi ducimus impedit.<br/>  Deserunt ipsa suscipit libero id! Iusto facere, quibusdam reiciendis iste libero in veniam deserunt repellendus placeat eius, dolorum beatae inventore perspiciatis minus. Voluptates, cum nesciunt laborum nobis inventore tempora enim voluptate aliquam? Praesentium ea cum repellendus veritatis velit, officiis optio nulla! Magni perferendis architecto assumenda quia ad! Inventore iste, quasi mollitia obcaecati eligendi rem! Culpa cum voluptatum suscipit sapiente, natus neque expedita eum ullam, aliquam, dignissimos accusamus omnis ea ipsam odio iusto recusandae!</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam explicabo libero, eaque officiis deserunt corporis, accusamus, a et earum voluptatem enim mollitia animi totam modi ducimus impedit.<br/>  Deserunt ipsa suscipit libero id! Iusto facere, quibusdam reiciendis iste libero in veniam deserunt repellendus placeat eius, dolorum beatae inventore perspiciatis minus. Voluptates, cum nesciunt laborum nobis inventore tempora enim voluptate aliquam? Praesentium ea cum repellendus veritatis velit, officiis optio nulla! Magni perferendis architecto assumenda quia ad! Inventore iste, quasi mollitia obcaecati eligendi rem! Culpa cum voluptatum suscipit sapiente, natus neque expedita eum ullam, aliquam, dignissimos accusamus omnis ea ipsam odio iusto recusandae!</p>

        
        </div>
    )
}

export default HomePage
